v1.1.6 (2018-02-21)
- added 'videos' to icon
- for json now using plugin://-url instead of http-url
- website changed: fixed playing of youtube videos
- removing non-ascii characters in title in parameters to prevent
UnicodeDecodeError: 'ascii' codec can't decode ...
The error occured when doing urllib.parse.parse_qs of the parameters